### ISSUE TITLE
Gradle issues with Git control

### ISSUE THREAD

**Issue by The-Wightman** [Kirimson/Jumazy#4]
Since moving the project to incorporate gradle ,eclipse git plugin control with versions of eclipse neon and before will cause the repository to delete itself or produce an "unable to update repository" error.

We do not currently have a means to prevent this issue unless we migrate to newer versions of software.

Discussion and testing with @Kirimson  and @JawwadC on newer versions of eclipse should help improve our understanding of the issue.

**Steps of reproduction**
- Download repository through Eclipse neon or previous Git console.
- Attempt to pull a newer version of the project through eclipse >> team >> pull menu

**Comment by The-Wightman** [comment]
@Kirimson  @JawwadC #2

**Comment by shayankb** [comment]
@Kirimson @JawwadC #3

**Comment by Kirimson** [comment]
This "unable to update repository" error is new to me. By "in built Git version control" I'm guessing you mean the Eclipse git plugin?

Are you trying to update the repo from Eclipse itself? I haven't done that before myself. Nut I've found no issues by pulling the repo from some git client like shell or desktop. Unless this is what you are doing and I'm just reading it all wrong.

Since libGDX uses multiple projects connected together I can imagine Eclipse getting a bit confused with stuff, even though it probably shouldn't. Either way, we can look more into your issue later today.
